#!/usr/bin/env python3
"""Regenerate docs/validation/rules.md and policies.md from the policy bundle.

Run from anywhere:  python3 scripts/docs/gen-policy-docs.py
Requires: pyyaml  (pip install pyyaml)
"""
import re
import pathlib
import yaml

REPO = pathlib.Path(__file__).resolve().parents[2]
BUNDLE = REPO / "policy-based-validation-plugin/src/main/resources/api-policy"
OUT = REPO / "docs/validation"

manifest = yaml.safe_load((BUNDLE / "PolicyBundle.yaml").read_text())


def split_front_matter(text):
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    return yaml.safe_load(m.group(1)), m.group(2)


def h1_title(body):
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def first_para(body):
    lines, started = [], False
    for line in body.splitlines():
        s = line.strip()
        if not started:
            if not s or s.startswith("#"):
                continue
            started = True
        if started:
            if not s or s.startswith("#"):
                break
            lines.append(s)
    return " ".join(lines)


def title_tail(t):
    return t.split("—", 1)[-1].strip() if "—" in t else t


rules = {}
for rid, rel in manifest["rules"].items():
    fm, body = split_front_matter((BUNDLE / rel).read_text())
    rules[rid] = {
        "id": rid,
        "category": fm.get("category", "Uncategorised"),
        "rule": fm.get("matcher", ""),
        "title": h1_title(body),
    }

policies = {}
for pid, rel in manifest["policies"].items():
    fm, body = split_front_matter((BUNDLE / rel).read_text())
    disp = {}
    for k, v in (fm.get("rules") or {}).items():
        if isinstance(v, dict):
            pts = v.get("points")
            disp[k] = ("PROHIBITED" if pts == "PROHIBITED" else pts, v.get("parameters") or {})
        elif v == "PROHIBITED":
            disp[k] = ("PROHIBITED", {})
        else:
            disp[k] = (v, {})
    policies[pid] = {"id": fm.get("id", pid), "intent": first_para(body), "dispositions": disp}

policy_ids = list(policies)
short = {p: p.replace("Enterprise Grade", "Enterprise").replace("Zalando Extended", "Zal. Ext.") for p in policy_ids}

# ---- rules.md ----
by_cat = {}
for r in rules.values():
    by_cat.setdefault(r["category"], []).append(r)

lines = [
    "# Rule Catalogue",
    "",
    "<!-- Generated by scripts/docs/gen-policy-docs.py — do not edit by hand. -->",
    "",
    "Every rule in the bundled **Areté Policy Engine** policy bundle, grouped",
    "by category. A rule is only evaluated when a [policy](policies.md) references",
    "it. See [the policy engine](policy-engine.md) for how matchers, rules, and",
    "policies fit together.",
    "",
    f"There are **{len(rules)} rules** across **{len(by_cat)} categories**, built on",
    f"**{len(manifest['matchers'])} matchers**.",
    "",
    '!!! note "Reading the policy columns"',
    "    A number is the point deduction applied once if the rule matches;",
    "    **P** marks a `PROHIBITED` disposition (any match forces the score to 0);",
    "    a blank cell means that policy does not include the rule.",
    "",
]
for cat in sorted(by_cat):
    lines += [f"## {cat}", ""]
    lines.append("| Rule | Title | Rule | " + " | ".join(short[p] for p in policy_ids) + " |")
    lines.append("|---|---|---|" + "|".join(["---"] * len(policy_ids)) + "|")
    for r in sorted(by_cat[cat], key=lambda x: x["id"]):
        cells = []
        for p in policy_ids:
            d = policies[p]["dispositions"].get(r["id"])
            cells.append("" if d is None else ("**P**" if d[0] == "PROHIBITED" else str(d[0])))
        lines.append(f"| `{r['id']}` | {title_tail(r['title'])} | `{r['rule']}` | " + " | ".join(cells) + " |")
    lines.append("")
(OUT / "rules.md").write_text("\n".join(lines))

# ---- policies.md ----
lines = [
    "# Policies",
    "",
    "<!-- Generated by scripts/docs/gen-policy-docs.py — do not edit by hand. -->",
    "",
    "A **policy** is the deployable rule set: the list of active [rules](rules.md)",
    "and what each one costs. The Areté Policy Engine exposes one rule set per",
    "policy in the bundle; pick one in the validation picker. The first policy",
    "listed here is the default when an unknown rule set is requested.",
    "",
    "```",
    "qualityScore   = max(0, 100 − Σ deductions for matched rules)",
    "effectiveScore = 0 if any PROHIBITED rule matched, else qualityScore",
    "```",
    "",
]
for pid, pol in policies.items():
    active = pol["dispositions"]
    prohibited = [k for k, v in active.items() if v[0] == "PROHIBITED"]
    overrides = {k: v[1] for k, v in active.items() if v[1]}
    lines += [f"## {pol['id']}", ""]
    if pol["intent"]:
        lines += [pol["intent"], ""]
    lines.append(f"- **{len(active)}** rules active" + (f", **{len(prohibited)}** prohibited" if prohibited else ""))
    lines.append("")
    if overrides:
        lines += ["Parameter overrides:", "", "| Rule | Overrides |", "|---|---|"]
        for k, ov in sorted(overrides.items()):
            lines.append(f"| `{k}` | " + ", ".join(f"`{a}` = `{b}`" for a, b in ov.items()) + " |")
        lines.append("")
    lines += [f'??? example "All {len(active)} rules in {pol["id"]}"', "",
              "    | Rule | Disposition | Title |", "    |---|---|---|"]
    for k, d in active.items():
        disp = "PROHIBITED" if d[0] == "PROHIBITED" else f"−{d[0]}"
        lines.append(f"    | `{k}` | {disp} | {title_tail(rules.get(k, {}).get('title', ''))} |")
    lines.append("")
(OUT / "policies.md").write_text("\n".join(lines))

print(f"wrote {OUT/'rules.md'} and {OUT/'policies.md'}")
